### PR TITLE
Hide exceptions from HistoryReplier

### LINKED ISSUE #2646: [BUG] NoSuchElementException: None.get
**Describe the bug**
There are frequent (once per couple minutes) errors in the Node log:
```
Oct 03 11:12:48 rock64 waves[10468]: INFO  c.w.s.BlockchainUpdaterImpl - New height: 1733623
Oct 03 11:12:48 rock64 waves[10468]: ERROR c.w.network.HistoryReplier - Error executing task
Oct 03 11:12:48 rock64 waves[10468]: com.google.common.util.concurrent.UncheckedExecutionException: java.util.NoSuchElementException: None.get
Oct 03 11:12:48 rock64 waves[10468]:         at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
Oct 03 11:12:48 rock64 waves[10468]:         at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
Oct 03 11:12:48 rock64 waves[10468]:         at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
Oct 03 11:12:48 rock64 waves[10468]:         at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
Oct 03 11:12:48 rock64 waves[10468]:         at com.wavesplatform.network.HistoryReplier.$anonfun$channelRead$7(HistoryReplier.scala:59)
Oct 03 11:12:48 rock64 waves[10468]:         at monix.eval.internal.TaskRunLoop$.startFuture(TaskRunLoop.scala:494)
Oct 03 11:12:48 rock64 waves[10468]:         at monix.eval.Task.runToFutureOpt(Task.scala:585)
Oct 03 11:12:48 rock64 waves[10468]:         at monix.eval.Task.runToFuture(Task.scala:541)
Oct 03 11:12:48 rock64 waves[10468]:         at com.wavesplatform.utils.ScorexLogging$TaskExt.runAsyncLogErr(ScorexLogging.scala:66)
Oct 03 11:12:48 rock64 waves[10468]:         at com.wavesplatform.network.HistoryReplier.channelRead(HistoryReplier.scala:65)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
Oct 03 11:12:48 rock64 waves[10468]:         at com.wavesplatform.network.PeerSynchronizer.channelRead(PeerSynchronizer.scala:55)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
Oct 03 11:12:48 rock64 waves[10468]:         at com.wavesplatform.network.TrafficLogger.channelRead(TrafficLogger.scala:41)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
Oct 03 11:12:48 rock64 waves[10468]:         at com.wavesplatform.network.DiscardingHandler.channelRead(DiscardingHandler.scala:18)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
Oct 03 11:12:48 rock64 waves[10468]:         at com.wavesplatform.network.TrafficWatcher.channelRead(TrafficWatcher.scala:47)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
Oct 03 11:12:48 rock64 waves[10468]:         at com.wavesplatform.network.BrokenConnectionDetector.channelRead(BrokenConnectionDetector.scala:17)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
Oct 03 11:12:48 rock64 waves[10468]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Oct 03 11:12:48 rock64 waves[10468]:         at java.lang.Thread.run(Thread.java:748)
Oct 03 11:12:48 rock64 waves[10468]: Caused by: java.util.NoSuchElementException: None.get
Oct 03 11:12:48 rock64 waves[10468]:         at scala.None$.get(Option.scala:529)
Oct 03 11:12:48 rock64 waves[10468]:         at scala.None$.get(Option.scala:527)
Oct 03 11:12:48 rock64 waves[10468]:         at com.wavesplatform.network.HistoryReplier$$anon$1.load(HistoryReplier.scala:27)
Oct 03 11:12:48 rock64 waves[10468]:         at com.wavesplatform.network.HistoryReplier$$anon$1.load(HistoryReplier.scala:24)
Oct 03 11:12:48 rock64 waves[10468]:         at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
Oct 03 11:12:48 rock64 waves[10468]:         at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
Oct 03 11:12:48 rock64 waves[10468]:         at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
Oct 03 11:12:48 rock64 waves[10468]:         at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
Oct 03 11:12:48 rock64 waves[10468]:         ... 65 common frames omitted
Oct 03 11:12:48 rock64 waves[10468]: INFO  c.w.s.BlockchainUpdaterImpl - MicroBlock(5ficwpH... -> Nn5Y3jY..., txs=6) appended
Oct 03 11:12:54 rock64 waves[10468]: INFO  c.w.s.BlockchainUpdaterImpl - MicroBlock(3WTQnZt... -> 5ficwpH..., txs=40) appended
```
**Additional context**
These problems seem to be started several days ago, after Feature 14 approved

### PR DESCRIPTION
**Pull request by phearnot**
Resolves #2646

### CODE REVIEW

File: node/src/main/scala/com/wavesplatform/http/DebugApiRoute.scala [hunk 1]
```diff
@@ -54,6 +54,7 @@ case class DebugApiRoute(
     peerDatabase: PeerDatabase,
     establishedConnections: ConcurrentMap[Channel, PeerInfo],
     rollbackTask: ByteStr => Task[Either[ValidationError, Seq[Block]]],
+    discardedTxsToUtx: Seq[Transaction] => Unit,
```
Comment (phearnot) [inline node/src/main/scala/com/wavesplatform/http/DebugApiRoute.scala]: Instead of having three rollback-related arguments, I suggest adding just one like
```scala
rollbackTask: (ByteStr, Boolean) => Task[Either[ValidationError, Unit]]
```
This task will perform rollback, return transactions to UTX if needed and broadcast local score to peers.
